# Generated by Django 2.0.3 on 2018-06-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='polygon',
            table='polygon',
        ),
        migrations.AlterModelTable(
            name='polypoint',
            table='polygon_point',
        ),
    ]
