# Generated by Django 2.0.3 on 2019-02-27 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('modification_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('confirms', models.ManyToManyField(related_name='confirms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='ProblemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=128, unique=True, upload_to='static/img')),
                ('is_active', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
            options={
                'db_table': 'problem_image',
            },
        ),
        migrations.CreateModel(
            name='ProblemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('verbose_name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(max_length=4096)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'problem_state',
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('verbose_name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(max_length=4096)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'problem_type',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemState'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ProblemType'),
        ),
        migrations.AddField(
            model_name='problem',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('latitude', 'longitude')},
        ),
    ]
