# Generated by Django 2.0.3 on 2018-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
