# Generated by Django 2.0.3 on 2019-03-14 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='favourite_problems',
            field=models.ManyToManyField(db_table='fav_problems', related_name='favourite_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
