# Generated by Django 2.0.3 on 2018-06-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20180610_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='verbose_name',
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
