# Generated by Django 2.0.3 on 2018-06-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20180617_2221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AlterModelTable(
            name='problem',
            table='problem',
        ),
        migrations.AlterModelTable(
            name='problemimage',
            table='problem_image',
        ),
        migrations.AlterModelTable(
            name='problemstate',
            table='problem_state',
        ),
        migrations.AlterModelTable(
            name='problemtype',
            table='problem_type',
        ),
    ]
