# Generated by Django 2.0.3 on 2019-02-25 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=128, unique=True, upload_to='static/img')),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'feedback_image',
            },
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gauth.Feedback'),
        ),
    ]
