# Generated by Django 2.0.3 on 2018-04-03 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tree.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tree_state', models.IntegerField(choices=[(0, 'HEALTHY'), (1, 'DRY'), (2, 'BROKEN'), (3, 'TOPING'), (4, 'MISTLETOE'), (5, 'DYING')])),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('confirms', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=models.SET(tree.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=128, upload_to='static/img')),
                ('visible', models.BooleanField(default=False)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='treesort',
            name='tree_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.TreeType'),
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_sort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.TreeSort'),
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.TreeType'),
        ),
    ]
