# Generated by Django 2.0.3 on 2019-02-27 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tree.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tree_state', models.IntegerField(choices=[(1, 'HEALTHY'), (2, 'DRY'), (3, 'BROKEN'), (4, 'TOPING'), (5, 'MISTLETOE'), (6, 'DYING')])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('confirms', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=models.SET(tree.models.get_sentinel_user), related_name='trees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tree',
            },
        ),
        migrations.CreateModel(
            name='TreeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(max_length=128, unique=True, upload_to='static/img')),
                ('visible', models.BooleanField(default=False)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tree.Tree')),
            ],
            options={
                'db_table': 'tree_image',
            },
        ),
        migrations.CreateModel(
            name='TreeSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'tree_sort',
            },
        ),
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'tree_type',
            },
        ),
        migrations.AddField(
            model_name='treesort',
            name='tree_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.TreeType'),
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_sort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.TreeSort'),
        ),
        migrations.AddField(
            model_name='tree',
            name='tree_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.TreeType'),
        ),
        migrations.AlterUniqueTogether(
            name='tree',
            unique_together={('latitude', 'longitude')},
        ),
    ]
