# Generated by Django 2.0.3 on 2018-05-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='long',
            new_name='longitude',
        ),
    ]
