# Generated by Django 2.0.3 on 2019-03-13 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='favourite_trees',
            field=models.ManyToManyField(db_table='fav_trees', related_name='favourite_trees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tree',
            name='confirms',
            field=models.ManyToManyField(related_name='confirmed_trees', to=settings.AUTH_USER_MODEL),
        ),
    ]
