# Generated by Django 2.0.3 on 2018-05-23 14:11

from django.conf import settings
from django.db import migrations, models
import tree.models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20180518_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(tree.models.get_sentinel_user), related_name='trees', to=settings.AUTH_USER_MODEL),
        ),
    ]
