# Generated by Django 2.0.3 on 2018-05-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20180523_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tree',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
