# Generated by Django 2.0.3 on 2018-05-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20180523_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeimages',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tree.Tree'),
        ),
        migrations.AlterField(
            model_name='treeimages',
            name='url',
            field=models.ImageField(max_length=128, unique=True, upload_to='static/img'),
        ),
    ]
