# Generated by Django 2.0.3 on 2018-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_polygon_polypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
