# Generated by Django 2.0.3 on 2018-06-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_auto_20180526_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treesort',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='treetype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tree',
            unique_together={('latitude', 'longitude')},
        ),
    ]
