# Generated by Django 2.0.3 on 2018-06-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_auto_20180603_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polypoint',
            name='poly',
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
        migrations.DeleteModel(
            name='PolyPoint',
        ),
    ]
