# Generated by Django 2.0.3 on 2018-06-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_auto_20180610_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='tree_state',
            field=models.IntegerField(choices=[(1, 'HEALTHY'), (2, 'DRY'), (3, 'BROKEN'), (4, 'TOPING'), (5, 'MISTLETOE'), (6, 'DYING')]),
        ),
    ]
